### ISSUE TITLE
Maps are included in NPM package v4.5.0, but source files are missing

### ISSUE THREAD

**Issue by asarapas** [czeckd/angular-dual-listbox#65]
Map files starts:
`{"version":3,"sources":["../tmp/<file_name>.ts"],"names":[],"mappings":...`

But those files are missing

**Comment by czeckd** [comment]
Thanks. The source files should now be there with v4.5.1.

**Comment by czeckd** [comment]
```
ERROR in ./node_modules/angular-dual-listbox/dual-list.component.ts
Module build failed: Error: /www/core-ui/node_modules/angular-dual-listbox/dual-list.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/www/core-ui/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/www/core-ui/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/angular-dual-listbox/angular-dual-listbox.module.js 4:0-58
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```
Seems like putting source files in the package violates the [APF v5.0](https://goo.gl/jB3GVv). Will revert in v4.5.2.

**Comment by czeckd** [comment]
As of angular-dual-list-box@v4.6.1, following Angular Package Format v5.0 format for the package. The spec doesn't put source files in the package, so will continue not to add them.
